### ISSUE TITLE
How to use this for dummies?

### ISSUE THREAD

**Issue by danielmarschall** [justusjonas74/uic-918-3#15]
Hello,

I am trying to use this script to decode a ticket. Unfortunately, I have no experience with node or npm.

I tried the following (running on a Debian system as a normal user, not root):

```
git clone https://github.com/justusjonas74/uic-918-3.git
cd uic-918-3
npm install
```

Then I created test_new.js with the following contents:

```
const uic = require('uic-918-3');

const options = {
    verifySignature: true
}

file_path = "ticket.png";

uic.readBarcode(file_path, options).then((ticket)=>{
        console.log(ticket); // I hope this decodes everything???
});

```

Now I try to execute it by running `node test_neu.js` and I get the following errors:

```
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module 'uic-918-3'
Require stack:
- /daten/homes/daniel-marschall/test/bahn/test_neu.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/daten/homes/daniel-marschall/test/bahn/test_neu.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/.../bahn/test_neu.js' ]
}

Node.js v18.19.0
```

What am I doing wrong?

---

**_What I want to achieve:_**

- I want to display all data from a ticket, like in https://github.com/rumpeltux/onlineticket/ --> is this possible?

- I have collected a lot of old tickets, however I only have the hex dump of the codes, not the barcode images --> is it possible to interprete the hex dump instead of a barcode with your solution?

Thanks for your help!

**Comment by arnebr** [comment]
Hi Daniel,
my setup is like this:
I´ve cloned the repo. Did `npm install`.  And I´ve created the following scenario `samples/test.js`:

``` javascript
const uic = require('../index')
const binaryData = Buffer.from('2355543::::::::::...','hex') 

const ticket = uic.interpretBarcode(binaryData)
console.dir(ticket, { depth: null });

```

Be aware that the library is not full compatible with UIC 918-9. This will be indicated if you find a U_FLEX part in the ticket section, which does not show the correct data there. 

Here is an explanation:
```
The UIC barcode standard was adopted in 2006 as version UIC 918-3. The implementation at that time was based on a tabular recording of relevant ticket data in the barcode, which is displayed in this format on the control device during inspection. The layout-based procedure (TLB), which consists of at least the segments U_HEAD and U_TLAY, does not provide for automated evaluation of barcode contents and is considered outdated by today's standards. Therefore, further formats have been developed for optimized display on control devices (for example, the left-aligned (PLAIN) layout of the TLB, as well as manufacturer-specific layouts), all of which are widely known in the market under the designation UIC 918-3. Additionally, the functionality can vary depending on the interpretation of the TLB by different providers of control devices and software.

Therefore, an update of the UIC standard was carried out in 2018: Version 918-9. The new barcode standard includes, in addition to the contents already described in UIC 918-3, the definition of a structured component: Flexible Content Barcode (FCB). In the FCB component, data are encoded in a structured form so that the contained data can be specifically used for automated evaluation. The central barcode segment of the FCB is designated as U_FLEX.

The UIC 918-9 standard is an extension of UIC 918-3 and accordingly contains, among other things, the specification of both the FCB and the TLB. The Germany ticket (Deutschlandticket) is expected to make use of the backward compatibility of the standard during a transition period and use the necessary segments for both TLB and FCB. The TLB can be output either in the left-aligned PLAI layout or in the RCT2 format.
```

**Comment by danielmarschall** [comment]
Hallo Arne,

thank you so much for your fast help! Your code helped me very much.

I had collected 25 version 1 tickets over time , and 6 of these codes do not work (header check failed).
I wonder if I can send these codes to you so you can look over it? (I am not sure about posting them here, because the codes might contain personal data)

Your website [arnebr.de](https://arnebr.de/) seems to be down, so I am not sure if you have an email address under that domain.

I hope I might be able to help contributing to this project soon

Kind regards,
Daniel

**Comment by justusjonas74** [comment]
@danielmarschall You are welcome to send me the barcodes by e-mail to hello@francisdoege.com. I will check why the barcode cannot be read.

**Comment by danielmarschall** [comment]
I have noticed that there have been a lot of activity in the code, so I wanted to re-check my tickets in case something has changed.

Unfortunately, I cannot use node again. There is no "index.js" file anymore. What am I doing wrong?

```
git clone https://github.com/justusjonas74/uic-918-3/
cd uic-918-3
npm install
```

I get the confirmation from npm:

```
> uic-918-3@1.0.5 postinstall
> node postinstall/updateCerts.js

Load public keys from https://railpublickey.uic.org/download.php ...
Successfully loaded key file.
Loaded 46 public keys and saved under "keys.json".

> uic-918-3@1.0.5 prepare
> husky


up to date, audited 458 packages in 2s

82 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

---

Then create `show_tickets.js` with the following code:

```
const uic = require("uic-918-3")
ticket = uic.interpretBarcode("  hex code here ")
console.dir(ticket, { depth: null })
```

I get the error message:

```
Error: Cannot find module 'uic-918-3'
Require stack:
- .../show_tickets.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (.../show_tickets.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '.../show_tickets.js'
  ]
}
```

Note that I am in user-land, not root.

**Comment by justusjonas74** [comment]
Cloning the source code via github is usually not necessary. Instead, you should rather install the package via `npm install uic-918-3`. Then it will also find the module. 
If you absolutely have to do it the hard way, then you have to build and install the local uic package within your NPM project in which the file "show_tickets.js" is located:
```shell
git clone https://github.com/justusjonas74/uic-918-3/
cd uic-918-3
npm install
npm run build
cd path/to/your/show_tickets.js
# maybe npm init -y
npm install ./path/to/uic-918-3
```

**Comment by danielmarschall** [comment]
@justusjonas74 Thank you so much! I didn't expect that it is THAT simple to use this library!

**Comment by danielmarschall** [comment]
@justusjonas74 Maybe in the README.md you could describe these steps. Because it reads like `npm install uic-918-3` and `git clone ...` is the same. That it requires much more steps ( `npm run build` etc.) is not described there.
Thank you!
