### ISSUE TITLE
RSA signature validation vulnerability

### ISSUE THREAD

**Issue by matthiaslexer** [justusjonas74/uic-918-3#5]
Hi, 

First, thanks for you library!
Second, one of your dependencies (jsrasign) has a critical vulnerability. 

https://www.npmjs.com/advisories/1672

**Comment by justusjonas74** [comment]
@matthiaslexer : Thanks for using my library. 
I fixed that issue with [v0.4.1](https://github.com/justusjonas74/uic-918-3/releases/tag/v0.4.1)
